### ISSUE TITLE
/admin/fetch/posts is unprotected

### ISSUE THREAD

**Issue by alexghr** [michou/awesome-dropbox-flickr-blog#11]
An anonymous user can simply POST to `/admin/fetch/posts` to resync the blog posts from Dropbox.

**Comment by michou** [comment]
I'm not sure it works for a really anonymous user -- you did log in with Google first.

Also, looks like #12 is a duplicate.

**Comment by michou** [comment]
@alexghr the problem was that my decorator wasn't properly handling an already decorated function. Changed the order of the decorators, still have to learn how to properly handle this case :grin: 

Any hints?

**Comment by alexghr** [comment]
I used this [SO answer](http://stackoverflow.com/questions/739654/how-can-i-make-a-chain-of-function-decorators-in-python/1594484#1594484) and the official documentation when I learned how decorators work in Python.
